name: CodeCov

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    env:
      OS: ${{ matrix.os }}
      PYTHON: '3.12'
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.12
    - name: Generate Report
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt        
        pip install coverage requests-mock setuptools
        python setup.py install
        coverage run -m --source=emhass unittest
        coverage report
        coverage xml
    - name: Upload coverage reports to Codecov
      run: |
        # Replace `linux` below with the appropriate OS
        # Options are `alpine`, `linux`, `macos`, `windows`
        curl -Os https://uploader.codecov.io/latest/linux/codecov
        chmod +x codecov
        ./codecov -t ${CODECOV_TOKEN}